# Generated by Django 2.0.1 on 2018-07-11 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aux', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('etapa', models.CharField(choices=[('Idea', 'Idea'), ('Semilla', 'Semilla'), ('Etapa temprana', 'Etapa temprana'), ('Expansion', 'Expansion'), ('Internacionalización', 'Internacionalización')], default='Idea', max_length=255)),
                ('descripcion_empresa', models.CharField(default='d', max_length=511)),
                ('descripcion_equipo', models.CharField(default='d', max_length=511)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=255)),
                ('Q', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(blank=True, default=0, null=True)),
                ('respondido', models.BooleanField(default=False)),
                ('validado', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('RESUELTO', 'RESUELTO'), ('PENDIENTE', 'PENDIENTE'), ('CORREGIR', 'CORREGIR')], default='PENDIENTE', max_length=255)),
                ('fecha_termino', models.DateTimeField(blank=True)),
                ('dimension', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_base', models.BooleanField(default=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('sub_numero', models.IntegerField(blank=True, null=True)),
                ('ponderacion', models.IntegerField()),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('tipo_pregunta', models.CharField(blank=True, choices=[('a', 'Alternativa'), ('e', 'Elección')], default='a', max_length=1)),
                ('depende_de', models.ManyToManyField(blank=True, related_name='_preguntaclasificacion_depende_de_+', to='grupo4test.PreguntaClasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_base', models.BooleanField(default=False)),
                ('dimension', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('sub_numero', models.IntegerField(blank=True, null=True)),
                ('ponderacion', models.IntegerField(default=1)),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('tipo_pregunta', models.CharField(blank=True, choices=[('a', 'Alternativa'), ('e', 'Elección')], default='a', max_length=1, null=True)),
                ('depende_de', models.ManyToManyField(blank=True, related_name='_preguntadiagnostico_depende_de_+', to='grupo4test.PreguntaDiagnostico')),
                ('etapas', models.ManyToManyField(to='grupo4test.Etapa')),
            ],
            options={
                'ordering': ['dimension', 'numero', 'sub_numero'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('respuesta', models.CharField(blank=True, max_length=255)),
                ('buena', models.BooleanField(default=False)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.FormDiagnostico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.PreguntaDiagnostico')),
            ],
            options={
                'ordering': ['formulario', 'pregunta__dimension', 'pregunta__numero', 'pregunta__sub_numero'],
            },
        ),
        migrations.CreateModel(
            name='RespuestasClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('respuesta', models.CharField(blank=True, max_length=255)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.FormularioClasificacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.PreguntaClasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tiempos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alternativa', models.CharField(max_length=255)),
                ('puntaje', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TipoElegir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_eleccion', models.CharField(max_length=255)),
                ('puntaje', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='preguntadiagnostico',
            name='preguntas_alternativa',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoAlternativa'),
        ),
        migrations.AddField(
            model_name='preguntadiagnostico',
            name='preguntas_eleccion',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoElegir'),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='preguntas_alternativa',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoAlternativa'),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='preguntas_eleccion',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoElegir'),
        ),
        migrations.AddField(
            model_name='formularioclasificacion',
            name='preguntas',
            field=models.ManyToManyField(through='grupo4test.RespuestasClasificacion', to='grupo4test.PreguntaClasificacion'),
        ),
        migrations.AddField(
            model_name='formdiagnostico',
            name='guardados',
            field=models.ManyToManyField(to='grupo4test.Tiempos'),
        ),
        migrations.AddField(
            model_name='formdiagnostico',
            name='preguntas',
            field=models.ManyToManyField(through='grupo4test.RespuestaDiagnostico', to='grupo4test.PreguntaDiagnostico'),
        ),
    ]
