# Generated by Django 2.0.6 on 2018-07-11 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pregunta', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ponderacion', models.IntegerField()),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('tipo_pregunta', models.CharField(blank=True, choices=[('a', 'Alternativa'), ('n', 'Número'), ('t', 'Texto'), ('d', 'Documento')], default='a', max_length=1)),
                ('base_question', models.BooleanField(default=False)),
                ('depende_de', models.ManyToManyField(blank=True, related_name='_preguntaclasificacion_depende_de_+', to='grupo4test.PreguntaClasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('respuesta', models.CharField(blank=True, max_length=255)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.FormularioClasificacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.PreguntaClasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alternativa', models.CharField(max_length=255)),
                ('puntaje', models.IntegerField()),
                ('hola', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoElegir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_eleccion', models.CharField(max_length=255)),
                ('puntaje', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='preguntas_alternativa',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoAlternativa'),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='preguntas_eleccion',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoElegir'),
        ),
        migrations.AddField(
            model_name='formularioclasificacion',
            name='preguntas',
            field=models.ManyToManyField(through='grupo4test.RespuestasClasificacion', to='grupo4test.PreguntaClasificacion'),
        ),
        migrations.AddField(
            model_name='formularioclasificacion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
