# Generated by Django 2.0.1 on 2018-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdiagnostico',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formdiagnostico',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preguntadiagnostico',
            name='dimension',
            field=models.CharField(choices=[('1', 'Modelo Negocio'), ('2', 'Gestión Organizacional'), ('3', 'Gestión Comercial'), ('4', 'Gestión Financiera'), ('5', 'Gestión de Innovación')], max_length=1),
        ),
    ]
