# Generated by Django 2.0.6 on 2018-07-11 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupo4test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('estado', models.CharField(choices=[(1, 'Idea'), (2, 'Semilla'), (3, 'Etapa temprana'), (4, 'Expansion'), (5, 'Internacionalización')], default=1, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='formularioclasificacion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tipoalternativa',
            name='hola',
        ),
        migrations.AddField(
            model_name='formularioclasificacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Cliente'),
        ),
    ]
