# Generated by Django 2.0.6 on 2018-06-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='asd',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
