# Generated by Django 2.0 on 2018-04-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='id',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='run',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
