# Generated by Django 2.0.6 on 2018-06-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0002_document_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='asd',
        ),
    ]
