# Generated by Django 2.0 on 2018-04-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0002_auto_20180426_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='email',
            field=models.EmailField(default='test@test.cl', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulante',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
