# Generated by Django 2.0.1 on 2018-07-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0003_remove_formdiagnostico_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='preguntas_alternativa',
            field=models.ManyToManyField(blank=True, default=None, to='grupo4test.TipoAlternativa'),
        ),
        migrations.AlterField(
            model_name='preguntadiagnostico',
            name='pregunta_base',
            field=models.BooleanField(default=True),
        ),
    ]
