# Generated by Django 2.0.6 on 2018-06-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0003_remove_document_asd'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Empresa'),
        ),
    ]
