# Generated by Django 2.0.6 on 2018-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0003_auto_20180711_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Idea', 'Idea'), ('Semilla', 'Semilla'), ('Etapa temprana', 'Etapa temprana'), ('Expansion', 'Expansion'), ('Internacionalización', 'Internacionalización')], default=1, max_length=255),
        ),
    ]
