# Generated by Django 2.0.1 on 2018-05-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0003_auto_20180426_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('etapa', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioClasificacion',
            fields=[
                ('id_formulario', models.IntegerField(primary_key=True, serialize=False)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaClasificacion',
            fields=[
                ('id_pregunta', models.IntegerField(primary_key=True, serialize=False)),
                ('ponderacion', models.IntegerField()),
                ('texto_pregunta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('respuesta', models.CharField(max_length=255)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.FormularioClasificacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.PreguntaClasificacion')),
            ],
        ),
        migrations.AddField(
            model_name='formularioclasificacion',
            name='preguntas',
            field=models.ManyToManyField(through='grupo4test.RespuestasClasificacion', to='grupo4test.PreguntaClasificacion'),
        ),
    ]
