# Generated by Django 2.0.6 on 2018-07-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0004_auto_20180711_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntaclasificacion',
            old_name='base_question',
            new_name='pregunta_base',
        ),
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='numero_pregunta',
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='sub_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
