# Generated by Django 2.0.1 on 2018-05-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0004_auto_20180519_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alternativa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoElegir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_eleccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='tipo_pregunta',
            field=models.CharField(blank=True, choices=[('a', 'Alternativa'), ('n', 'Número'), ('t', 'Texto'), ('e', 'Elegir')], default='a', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='preguntas_alternativa',
            field=models.ManyToManyField(to='grupo4test.TipoAlternativa'),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='preguntas_eleccion',
            field=models.ManyToManyField(to='grupo4test.TipoElegir'),
        ),
    ]
