# Generated by Django 2.0.6 on 2018-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0005_auto_20180616_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestadiagnostico',
            name='buena',
            field=models.BooleanField(default=False),
        ),
    ]
