# Generated by Django 2.0.6 on 2018-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0005_auto_20180711_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='etapa',
            field=models.CharField(choices=[('Idea', 'Idea'), ('Semilla', 'Semilla'), ('Etapa temprana', 'Etapa temprana'), ('Expansion', 'Expansion'), ('Internacionalización', 'Internacionalización')], default='Idea', max_length=255),
        ),
        migrations.AlterField(
            model_name='tipoalternativa',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipoelegir',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
