# Generated by Django 2.0.1 on 2018-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0006_auto_20180520_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='base_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='depende_de',
            field=models.ManyToManyField(blank=True, null=True, related_name='_preguntaclasificacion_depende_de_+', to='grupo4test.PreguntaClasificacion'),
        ),
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='preguntas_alternativa',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoAlternativa'),
        ),
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='preguntas_eleccion',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoElegir'),
        ),
        migrations.AlterField(
            model_name='respuestasclasificacion',
            name='respuesta',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
