# Generated by Django 2.0.6 on 2018-06-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0006_respuestadiagnostico_buena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestadiagnostico',
            options={'ordering': ['formulario', 'pregunta__Q', 'pregunta__numero', 'pregunta__sub_numero']},
        ),
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
