# Generated by Django 2.0.6 on 2018-07-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0006_auto_20180711_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aux', models.CharField(max_length=255)),
            ],
        ),
    ]
