# Generated by Django 2.0.6 on 2018-07-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0006_auto_20180712_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdiagnostico',
            name='porcentaje',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='formdiagnostico',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
