# Generated by Django 2.0.6 on 2018-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0007_auto_20180712_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempos',
            name='fecha_guardado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
