# Generated by Django 2.0.6 on 2018-07-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0007_aux'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(blank=True, default=0, null=True)),
                ('respondido', models.BooleanField(default=False)),
                ('validado', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('RESUELTO', 'RESUELTO'), ('PENDIENTE', 'PENDIENTE'), ('CORREGIR', 'CORREGIR')], default='PENDIENTE', max_length=255)),
                ('fecha_termino', models.DateTimeField(blank=True)),
                ('Q', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_base', models.BooleanField(default=False)),
                ('dimension', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('sub_numero', models.IntegerField(blank=True, null=True)),
                ('ponderacion', models.IntegerField(default=1)),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('tipo_pregunta', models.CharField(blank=True, choices=[('a', 'Alternativa'), ('n', 'Número'), ('t', 'Texto'), ('d', 'Documento')], default='a', max_length=1, null=True)),
                ('depende_de', models.ManyToManyField(blank=True, related_name='_preguntadiagnostico_depende_de_+', to='grupo4test.PreguntaDiagnostico')),
                ('preguntas_alternativa', models.ManyToManyField(blank=True, to='grupo4test.TipoAlternativa')),
                ('preguntas_eleccion', models.ManyToManyField(blank=True, to='grupo4test.TipoElegir')),
            ],
            options={
                'ordering': ['dimension', 'numero', 'sub_numero'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('respuesta', models.CharField(blank=True, max_length=255)),
                ('buena', models.BooleanField(default=False)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.FormDiagnostico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo4test.PreguntaDiagnostico')),
            ],
            options={
                'ordering': ['formulario', 'pregunta__dimension', 'pregunta__numero', 'pregunta__sub_numero'],
            },
        ),
        migrations.CreateModel(
            name='Tiempos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='formdiagnostico',
            name='guardados',
            field=models.ManyToManyField(to='grupo4test.Tiempos'),
        ),
        migrations.AddField(
            model_name='formdiagnostico',
            name='preguntas',
            field=models.ManyToManyField(through='grupo4test.RespuestaDiagnostico', to='grupo4test.PreguntaDiagnostico'),
        ),
    ]
