# Generated by Django 2.0.6 on 2018-06-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0007_auto_20180623_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extension',
            field=models.CharField(default='none', max_length=8),
        ),
    ]
