# Generated by Django 2.0.1 on 2018-05-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0007_auto_20180521_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='depende_de',
            field=models.ManyToManyField(blank=True, related_name='_preguntaclasificacion_depende_de_+', to='grupo4test.PreguntaClasificacion'),
        ),
    ]
