# Generated by Django 2.0.1 on 2018-05-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0009_preguntaclasificacion_numero_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='base_question',
        ),
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='depende_de',
        ),
    ]
