# Generated by Django 2.0.1 on 2018-07-06 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupo4test', '0010_formdiagnostico_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaclasificacion',
            options={'ordering': ['numero_pregunta']},
        ),
        migrations.RemoveField(
            model_name='formularioclasificacion',
            name='empresa',
        ),
        migrations.AddField(
            model_name='formdiagnostico',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formularioclasificacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='preguntas_eleccion',
            field=models.ManyToManyField(blank=True, to='grupo4test.TipoElegir'),
        ),
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='numero_pregunta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='texto_pregunta',
            field=models.CharField(default='question', max_length=255),
        ),
    ]
