# Generated by Django 2.0.1 on 2018-05-23 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0011_empresa_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='base_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='depende_de',
            field=models.ManyToManyField(blank=True, related_name='_preguntaclasificacion_depende_de_+', to='grupo4test.PreguntaClasificacion'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='etapa',
            field=models.CharField(blank=True, default='TBD', max_length=255, null=True),
        ),
    ]
