# Generated by Django 2.0.1 on 2018-07-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0011_formdiagnostico_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioclasificacion',
            name='empresa',
        ),
    ]
