# Generated by Django 2.0.1 on 2018-07-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0012_remove_formularioclasificacion_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioclasificacion',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Empresa'),
        ),
    ]
