# Generated by Django 2.0.1 on 2018-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0012_auto_20180706_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='texto_pregunta',
            field=models.CharField(default='question', max_length=255),
        ),
    ]
