# Generated by Django 2.0.1 on 2018-05-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0012_auto_20180523_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='papa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='tipo_pregunta',
            field=models.CharField(blank=True, choices=[('a', 'Alternativa'), ('n', 'Número'), ('t', 'Texto')], default='a', max_length=1, null=True),
        ),
    ]
