# Generated by Django 2.0.1 on 2018-07-06 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupo4test', '0013_formularioclasificacion_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioclasificacion',
            name='empresa',
        ),
        migrations.AddField(
            model_name='formularioclasificacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
