# Generated by Django 2.0.1 on 2018-05-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0013_auto_20180523_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntaclasificacion',
            old_name='papa',
            new_name='padre',
        ),
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='preguntas_eleccion',
        ),
    ]
