# Generated by Django 2.0.1 on 2018-07-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0013_preguntaclasificacion_texto_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='numero_pregunta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
