# Generated by Django 2.0.1 on 2018-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0014_auto_20180526_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioclasificacion',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
