# Generated by Django 2.0.1 on 2018-07-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0014_auto_20180706_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaclasificacion',
            options={'ordering': ['numero_pregunta']},
        ),
    ]
