# Generated by Django 2.0.1 on 2018-07-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0015_auto_20180706_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApareceEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(default='', max_length=255)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(default='', max_length=255)),
                ('numero', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='preguntadiagnostico',
            options={'ordering': ['dimension__numero', 'numero', 'sub_numero']},
        ),
        migrations.RemoveField(
            model_name='preguntadiagnostico',
            name='Q',
        ),
        migrations.AddField(
            model_name='preguntadiagnostico',
            name='aparece_en',
            field=models.ManyToManyField(to='grupo4test.ApareceEn'),
        ),
        migrations.AddField(
            model_name='preguntadiagnostico',
            name='dimension',
            field=models.ForeignKey(default='hola', on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Dimension'),
            preserve_default=False,
        ),
    ]
