# Generated by Django 2.0.1 on 2018-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0015_formularioclasificacion_respondido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='base_question',
        ),
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='padre',
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='hijo_de',
            field=models.IntegerField(default=0),
        ),
    ]
