# Generated by Django 2.0.1 on 2018-05-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0016_auto_20180526_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='hijo_de',
        ),
    ]
