# Generated by Django 2.0.1 on 2018-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0016_auto_20180706_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntadiagnostico',
            options={'ordering': ['Q', 'numero', 'sub_numero']},
        ),
        migrations.RemoveField(
            model_name='preguntadiagnostico',
            name='aparece_en',
        ),
        migrations.RemoveField(
            model_name='preguntadiagnostico',
            name='dimension',
        ),
        migrations.AddField(
            model_name='preguntadiagnostico',
            name='Q',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ApareceEn',
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
    ]
