# Generated by Django 2.0.1 on 2018-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0018_auto_20180526_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='base_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preguntaclasificacion',
            name='hijo_de',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='depende_de',
            field=models.ManyToManyField(blank=True, related_name='_preguntaclasificacion_depende_de_+', to='grupo4test.PreguntaClasificacion'),
        ),
    ]
