# Generated by Django 2.0.1 on 2018-05-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0019_auto_20180526_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaclasificacion',
            name='hijo_de',
        ),
    ]
