# Generated by Django 2.0.1 on 2018-05-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0020_remove_preguntaclasificacion_hijo_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioclasificacion',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
