# Generated by Django 2.0.1 on 2018-05-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0021_formularioclasificacion_validado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaclasificacion',
            name='numero_pregunta',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
