# Generated by Django 2.0.1 on 2018-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0024_auto_20180529_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoalternativa',
            name='puntaje',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
