# Generated by Django 2.0.6 on 2018-06-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupo4test', '0026_ejemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrpcion', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('sub_numero', models.IntegerField(blank=True, null=True)),
                ('Q', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Q5', 'Q5')], max_length=4)),
                ('ponderacion', models.IntegerField()),
                ('texto_pregunta', models.CharField(max_length=255)),
                ('tipo_pregunta', models.CharField(blank=True, choices=[('a', 'Alternativa'), ('n', 'Número'), ('t', 'Texto')], default='a', max_length=1, null=True)),
                ('base_question', models.BooleanField(default=False)),
                ('depende_de', models.ManyToManyField(blank=True, related_name='_preguntadiagnostico_depende_de_+', to='grupo4test.PreguntaDiagnostico')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupo4test.Documento')),
                ('preguntas_alternativa', models.ManyToManyField(blank=True, to='grupo4test.TipoAlternativa')),
            ],
        ),
    ]
